DefaultContentLanguage: 'fr'
languageCode: 'fr'

title: Club d’athlétisme Corsaire-Chaparral
baseURL: "https://www.corsaire-chaparral.org" # the base hostname & protocol for your site
copyright: Tous droits réservés.

publishDir: public

permalinks:
  nouvelles: nouvelles/:year/:month/:day/:slug

hrefTargetBlank: true

# Build pages with 'future' date
buildFuture: true

params:
  themeColor: '#f26e21'
  description: >
    Situé dans les Basses-Laurentides, le club d’athlétisme Corsaire-Chaparral est un organisme sans but lucratif dont la mission est de promouvoir l’athlétisme auprès des jeunes.
  facebook: "CorsaireChaparral"
  twitter: "CorsaireC"
  instagram: "corsairechaparral"
  email: info@corsaire-chaparral.org
  adminEmail: louis@corsaire-chaparral.org
  admin: Louis-Olivier Brassard
#  annonce: >
#   Championnats 2019 Champs <a href="/resultats/direct/" class="btn btn-primary -sm">Résultats 🔥</a>

paginate: 12
paginatePath: page

markup:
  tableOfContents:
    endLevel: 2
  goldmark:
    renderer:
        unsafe: true

menu:
  main:
  - identifier: horaire-inscription
    title: Horaire et inscription
    weight: 10
  - identifier: inscription
    title: Inscription
    url: '/inscription/'
    parent: horaire-inscription
    weight: 20
  - identifier: entrainements
    url: '/club/entrainements/'
    title: Horaire des entraînements
    parent: horaire-inscription
    weight: 20
  - identifier: club
    title: Le club
    url: '/club/'
    weight: 10
  - identifier: histoire-mission
    title: Histoire et mission
    url: '/club/histoire-mission/'
    weight: 10
    parent: club
  - identifier: entraineurs
    url: '/club/entraineurs/'
    title: Entraîneurs
    parent: club
    weight: 40
  - identifier: benevolat
    url: '/club/benevolat/'
    title: Bénévolat
    parent: club
    weight: 50
  - identifier: vetements
    url: '/club/vetements/'
    title: Vêtements
    parent: club
    weight: 60
  - identifier: partenaires
    url: '/partenaires/'
    title: Partenaires
    parent: club
    weight: 70
  - identifier: liens-ressources
    url: '/club/liens-ressources/'
    title: Liens et ressources
    parent: club
    weight: 80
  - identifier: records-statistiques
    url: '/club/records-statistiques/'
    title: Records et statistiques
    parent: club
    weight: 90

  - identifier: nouvelles-evenements
    title: Nouvelles et événements
    weight: 30

  - identifier: nouvelles
    url: '/nouvelles/'
    title: Nouvelles
    parent: nouvelles-evenements
    weight: 20
  - identifier: competitions
    url: '/competitions/'
    title: Nos compétitions
    parent: nouvelles-evenements
    weight: 30

  - identifier: plan
    url: '/plan-du-site/'
    title: Plan du site
    weight: 50

  membres:
    - identifier: courriels
      title: Courriel web
      url: https://mail.corsaire-chaparral.org/
      weight: 80
