# the base hostname & protocol for your site
baseURL: "https://www-test.corsaire-chaparral.org"

title: "[TEST] Club d’athlétisme Corsaire-Chaparral"

params:
  stripePublicKey: pk_test_QfKSmWhXOWW9ZCkGdKtkL9p6
  apiUrl: https://api-test.corsaire-chaparral.org/v1/payment/new